name: Deploy to GitHub packages and Sonatype Snapshots

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests with Gradle
        run: ./gradlew allTests
      - name: Generate dokka HTML
        run: ./gradlew dokkaHtml
      - name: Deploy snapshot to Sonatype Snapshots
        run: ./gradlew -Porg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=1g" -Psnapshot=true publishAllPublicationsToSnapshotRepository
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Deploy snapshot to GitHub packages
        run: ./gradlew -Porg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=1g" -Psnapshot=true publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
